name: GitOps Pipeline with ArgoCD

on: 
    push:
        branches: 
            - main
        paths-ignore:
            - 'manifest/**' # ignore changes to manifest files to prevent loop
env: 
    PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
   
